category_name: services
service_name: photodrop
remote_dir_path: /home/{{ ansible_user }}/{{ category_name }}

docker_scaling_timeout: 7

app_environment:
  SERVER_PORT: 4500
  DB_HOST: "photodrop-postgresql"
  DB_PORT: 5432
  DB_USERNAME: "postgres"
  DB_PASSWORD: "{{ DB_PASSWORD }}"
  DB_NAME: "postgres"
  JWT_SECRET_KEY: "{{ JWT_SECRET_KEY }}"
