name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "*.md"

  pull_request:
    branches: [main]
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build -- --noEmit

      - name: Lint
        run: npm run lint -- --max-warnings=0
