name: Deploy

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'
      - 'test/**'

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Run Playbook
        uses: dawidd6/action-ansible-playbook@f2818df92e0627f4a84ef72e307a663a90ba764c
        with:
          playbook: ansible/main.yml
          key: ${{ secrets.ANSIBLE_PRIVATE_SSH_KEY }}
          inventory: |
            [dev_infrastructure]
            linux1   ansible_host=${{ secrets.ANSIBLE_HOST }}   ansible_port=${{ secrets.ANSIBLE_PORT }}   ansible_user=ansible
          options: |
            --extra-vars "DB_PASSWORD=${{ secrets.DB_PASSWORD }}"
            --extra-vars "ACCESS_TOKEN_KEY=${{ secrets.ACCESS_TOKEN_KEY }}"
